- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - include: tasks/systemvars.yml
    - include: tasks/homebrew.yml
    - include: tasks/oh-my-zsh.yml
 
