- hosts: localhost
  connection: local

  vars:
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
      - homebrew/dupes
      - homebrew/php
      - homebrew/versions
      - caskroom/versions
      - caskroom/drivers

    homebrew_installed_packages:
      - bash-completion
      - composer
      - dockutil
      - drush
      - git
      - micro
      - mcrypt
      - mysql
      - npm
      - openssl
      - php70
      - php70-mcrypt
      - php70-xdebug
      - python
      - ssh-copy-id
      - sqlite
      - vim
      - wget
      - zsh

    homebrew_cask_apps:
      - 1password
      - alfred
      - flux
      - google-chrome
      - iterm2
      - keybase
      - postman
      - querious
      - slack
      - sonos
      - spectacle
      - spotify
      - sublime-text
      - vagrant
      - virtualbox
      - viscosity

    dock_items:
      - name: Launchpad
        path: /Applications/Launchpad.app
        position: 1

      - name: Google Chrome
        path: '/Applications/Google Chrome.app'
        position: 2

      - name: Sublime Text
        path: '/Applications/Sublime Text.app'
        position: 3

      - name: Slack 
        path: /Applications/Slack.app
        position: 4
       
      - name: Messages
        path: /Applications/Messages.app
        position: 5

      - name: Querious 
        path: /Applications/Querious.app
        position: 6

      - name: Terminal
        path: /Applications/Utilities/Terminal.app
        position: 7

      - name: Sonos
        path: /Applications/Sonos.app
        position: 8

      - name: Notes
        path: /Applications/Notes.app 
        position: 9

      - name: System Preferences
        path: '/Applications/System Preferences.app'
        position: 10

    sublime_packages:
      - name: SublimePHPCompanion
        repo: https://github.com/erichard/SublimePHPCompanion
        version: v1.3.1

      - name: SublimeAllAutocomplete
        repo: https://github.com/alienhard/SublimeAllAutocomplete
        version: master

      - name: DocBlockr
        repo: https://github.com/spadgos/sublime-jsdocs
        version: 2.14.1

      - name: GitGutter
        repo: https://github.com/jisaacks/GitGutter
        version: 1.3.0

      - name: 'Material Theme'
        repo: https://github.com/equinusocio/material-theme
        version: v3.2.2

      - name: SublimeLinter3
        repo: https://github.com/SublimeLinter/SublimeLinter3
        version: 3.7.4

      - name: SublimeLinter-php
        repo: https://github.com/SublimeLinter/SublimeLinter-php
        version: 1.0.12

    ruby_gem_packages:
      - sass
      - bourbon
      - neat

    npm_packages:
      - gulp-cli

  roles:
    - geerlingguy.homebrew

  pre_tasks:
    - name: Get the current user
      shell: whoami
      register: macos_user
      become: no

    - name: Ensure correct permissions for homebrew binaries
      file:
        path: /usr/local/bin
        owner: "{{ macos_user.stdout }}"
        group: admin
        recurse: yes
      become: yes

  tasks:
    - name: Ensure homebrew apps are linked
      homebrew:
        name: "{{ item }}"
        state: linked
      with_items: "{{ homebrew_installed_packages }}"
      ignore_errors: true

    - include: tasks/dock.yml
    - include: tasks/git-fixup.yml
    - include: tasks/node.yml
    - include: tasks/oh-my-zsh.yml
    - include: tasks/ruby.yml
    - include: tasks/sublime.yml
    - include: tasks/wallpaper.yml
